---
   - hosts: all
     become: true
     become_method: sudo
     tasks:
             - name: "Removing Apache web-server 2.4 and MySQL Server 8.0"
               apt:
                       force_apt_get: true
                       name:
                               - apache2
                               - mysql-server
                       state: absent
