---
   - hosts: all
     become: true
     become_method: sudo
     tasks:
             - name: "Remove file (delete file)"
               ansible.builtin.file:
                       path: /etc/resolv.conf
                       state: absent
             - name: "Create /etc/resolv.conf with a first line 'nameserver 127.0.0.53'"
               ansible.builtin.lineinfile:
                       path: /etc/resolv.conf
                       line: nameserver 127.0.0.53
                       create: yes

             - name: "Setting other DNS client settings"
               blockinfile:
                       path: /etc/resolv.conf
                       #marker: "###"
                       insertafter: 'nameserver 127.0.0.53'
                       state: present
                       block: |
                               nameserver 172.16.168.10
                               options edns0 trust-ad
                               search ru-central1.internal auto.internal sfgak.local

             - name: "Update apt cache"
               apt:
                       force_apt_get: true
                       update_cache: yes
                       cache_valid_time: 86400 #One day
